import HeaderAuth from "../../HeaderAuth";
const guides=[
 ["01","Como fazer sua primeira doação","Passo a passo para escolher um pacote, identificar sua conta e concluir com segurança.","Equipe Echelon","6 min","1.248"],
 ["02","Pagamento via PIX","Como gerar o QR Code, confirmar o pagamento e acompanhar a aprovação automática.","Suporte RF","3 min","986"],
 ["03","Pagamento com cartão","Bandeiras aceitas, parcelamento, autenticação e análise de segurança.","Equipe Financeira","4 min","742"],
 ["04","Como receber seus Cash Points","Prazo de entrega, atualização do saldo e o que fazer se o crédito não aparecer.","Admin Echelon","5 min","1.106"],
 ["05","Histórico, bônus e reembolsos","Onde consultar transações, regras dos bônus progressivos e política de reembolso.","Suporte RF","7 min","654"]
];
const Brand=()=> <span className="brand"><span className="brand-mark">RF</span><span className="brand-copy"><strong>ECHELON</strong><small>PRIVATE SERVER</small></span></span>;
export default function DonationGuides(){return <main className="forum-page donation-guides-page"><header className="site-header forum-nav"><a href="/"><Brand/></a><nav><a href="/">Início</a><a href="/#download">Download</a><a className="active" href="/forum">Fórum</a><a href="/gamecp">Game CP</a></nav><div className="header-tools"><span className="lang-switch"><b>PT</b><a href="/en/forum">EN</a></span><HeaderAuth /></div></header>
 <section className="guide-hero"><div><span className="kicker">FÓRUM / DOAÇÕES & CASH POINTS</span><h1>Central de <em>doações.</em></h1><p>Tudo o que você precisa para contribuir com segurança e receber seus créditos sem complicação.</p></div><a className="corner-button" href="/gamecp">ABRIR LOJA DE CASH <b>↗</b></a></section>
 <section className="guide-index"><div className="guide-toolbar"><div><span>05</span><small>TUTORIAIS OFICIAIS</small></div><label><b>⌕</b><input aria-label="Pesquisar tutoriais" placeholder="Pesquisar nesta seção..."/></label><a href="/forum">← VOLTAR AO FÓRUM</a></div><div className="guide-list">{guides.map((g,i)=><a className="guide-topic" href={i===0?"/forum/doacoes/primeira-doacao":`#tutorial-${i+1}`} id={`tutorial-${i+1}`} key={g[0]}><span className="guide-number">{g[0]}</span><span className="guide-topic-icon">{i===0?"✦":"◈"}</span><span className="guide-main"><small>{i===0?"FIXADO · ESSENCIAL":"TUTORIAL OFICIAL"}</small><strong>{g[1]}</strong><p>{g[2]}</p><span>Por <b>{g[3]}</b> · Atualizado hoje</span></span><span className="guide-meta"><b>{g[4]}</b><small>LEITURA</small></span><span className="guide-meta"><b>{g[5]}</b><small>VISUALIZAÇÕES</small></span><i>→</i></a>)}</div><aside className="guide-help"><div><span>AINDA PRECISA DE AJUDA?</span><h2>Fale com o suporte.</h2><p>Nossa equipe pode verificar pagamentos e créditos diretamente na sua conta.</p></div><a href="/forum#04-1" className="corner-button">ABRIR ATENDIMENTO <b>↗</b></a></aside></section>
 </main>}
