import LaunchCountdown from "./LaunchCountdown";
import {serverRates,serverSystems} from "./config/site";
import {getServerStatus} from "./lib/game-account";
const topics=[["OFICIAL","Informações gerais do servidor","Equipe Echelon · Atualizado hoje","cyan"],["GUIA","Como instalar e começar a jogar","12 respostas · 328 visualizações","violet"],["COMUNIDADE","Recrutamento de guildas","38 respostas · há 18 min","amber"]];
const Brand=()=> <span className="brand"><span className="brand-mark">RF</span><span className="brand-copy"><strong>ECHELON</strong><small>PRIVATE SERVER</small></span></span>;
export default async function Home(){
 const live=await getServerStatus();
 const status=live.online===null
  ?[["Servidor","Indisponível"],["Jogadores","—"]]
  :[["Servidor",live.online?"Online":"Offline"],["Jogadores",live.online?String(live.playersOnline):"—"]];
 return <main className="home-page" id="conteudo">
 <header className="site-header"><a href="#inicio" aria-label="RF Echelon - início"><Brand/></a><nav aria-label="Navegação principal"><a href="#inicio">Início</a><a href="#taxas">Taxas</a><a href="#download">Download</a><a href="/doacao">Doação</a><a href="/forum">Fórum</a><a href="/conta">Minha conta</a></nav><div className="header-tools"><span className="lang-switch"><b>PT</b><a href="/en">EN</a></span><a className="header-cta" href="/conta">Criar conta <span>↗</span></a></div></header>
 <section className="hero" id="inicio"><div className="stars"/><div className="planet"/><div className="orb orb-one"/><div className="orb orb-two"/><div className="hero-grid"/><div className="launch-panel"><div className="launch-copy"><span>ABERTURA OFICIAL</span><strong>28/08 · 20:00</strong><small>BETA SEM WIPE</small></div><LaunchCountdown/><a className="launch-cta" href="/conta">CRIAR CONTA <b>↗</b></a></div><div className="hero-content"><div className="eyebrow"><span/> UMA NOVA ERA COMEÇA AGORA</div><h1>Eleve seu poder.<br/><em>Domine Novus.</em></h1><p>RF Echelon traz de volta a guerra clássica entre raças com evolução equilibrada, economia estável e batalhas épicas todos os dias.</p><div className="hero-actions"><a className="btn btn-primary" href="#download">Baixar o jogo <span>↓</span></a><a className="btn btn-ghost" href="/forum"><span className="play">▶</span> Conhecer o servidor</a></div><div className="season"><span>SEASON 01</span><div/><small>ASCENDA. CONQUISTE. DOMINE.</small></div></div><aside className="server-card"><div className="server-card-title"><span className={`pulse${live.online?"":" off"}`}/> STATUS DO SERVIDOR <small>{live.online===null?"—":live.online?"LIVE":"OFFLINE"}</small></div>{status.map(([l,v])=><div className="stat" key={l}><span>{l}</span><strong>{v}</strong></div>)}<div className="server-foot"><span>ACC</span><span>BEL</span><span>CORA</span></div></aside></section>
 <section className="section rates" id="taxas"><div className="section-intro"><span className="kicker">CONFIGURAÇÃO DO SERVIDOR</span><h2>Taxas pensadas pro <em>late game.</em></h2><p>Evolução rápida sem perder o desafio — confira as taxas e sistemas ativos no RF Echelon.</p></div><div className="rate-grid">{serverRates.map(r=><div className="rate-card" key={r.label}><span className="rate-value">{r.value}</span><span className="rate-label">{r.label}</span></div>)}</div><div className="system-list"><span className="mini-label">SISTEMAS</span>{serverSystems.map(s=><div className="system-row" key={s.name}><b className={`system-status ${s.active?"on":"off"}`}>{s.active?"ATIVO":"DESATIVADO"}</b><span><strong>{s.name}</strong>{"detail" in s&&<p>{s.detail}</p>}</span></div>)}</div><p className="rates-note">E muitos outros recursos — com mais chegando.</p></section>
 <section className="section download" id="download"><div className="section-intro"><span className="kicker">COMECE SUA JORNADA</span><h2>Pronto para a <em>batalha?</em></h2><p>O launcher ainda está sendo preparado. O download abre junto com o servidor.</p></div><div className="download-panel"><div className="file-icon">⏳</div><div><span className="mini-label">CLIENTE COMPLETO</span><h3>RF Echelon Launcher</h3><p>Disponível em 28/08/2026 às 20:00.</p></div><span className="btn btn-ghost" aria-disabled="true">Em breve</span></div><div className="requirements"><span><b>01</b> Crie sua conta na abertura</span><span><b>02</b> Baixe e instale o launcher</span><span><b>03</b> Entre e escolha sua raça</span></div></section>
 <section className="section donate" id="doacao"><div className="donate-copy"><span className="kicker">APOIE O ECHELON</span><h2>Sua força mantém<br/>este universo <em>vivo.</em></h2><p>As doações ajudam a manter a infraestrutura, segurança e novos eventos. As recompensas não substituem sua evolução dentro do jogo.</p><ul><li>Pagamento seguro</li><li>Crédito automático</li><li>Histórico disponível</li></ul></div><div className="donate-card"><span className="mini-label">PACOTES</span><div className="coins"><span>◈</span><div><strong>Em breve</strong><small>Cash Points + 30 dias Premium</small></div></div><div className="price" style={{fontSize:20}}>Divulgados na sexta-feira</div><a className="btn btn-gold" href="/doacao">Saber mais <span>↗</span></a><small className="safe">Abertura em 28/08/2026 às 20:00</small></div></section>
 <section className="section forum" id="forum"><div className="forum-head"><div><span className="kicker">CENTRAL DA COMUNIDADE</span><h2>Últimas do <em>fórum.</em></h2></div><a className="text-link" href="/forum">Ver todos os tópicos ↗</a></div><div className="forum-layout"><div className="topic-list">{topics.map((t,i)=><a className="topic" href={`/forum#topico-${i+1}`} key={t[1]}><span className={`topic-icon ${t[3]}`}>#</span><div><span className="topic-tag">{t[0]}</span><h3>{t[1]}</h3><p>{t[2]}</p></div><b>→</b></a>)}</div><aside className="forum-info"><span className="mini-label">INFORMAÇÕES RÁPIDAS</span><h3>Servidor PvP<br/>com progressão justa.</h3><dl><div><dt>Experiência</dt><dd>10x</dd></div><div><dt>Drop</dt><dd>5x</dd></div><div><dt>Max level</dt><dd>55</dd></div><div><dt>Chip War</dt><dd>3× ao dia</dd></div></dl><a href="/forum#informacoes">Ver informações completas →</a></aside></div></section>
 <footer><a href="#inicio"><Brand/></a><p>© 2026 CCR — Todos os direitos reservados.<br/>RF Online pertence aos seus respectivos proprietários. RF Echelon é um servidor independente criado por fãs.</p><div><a href="#download">Download</a><a href="/doacao">Doação</a><a href="/forum">Fórum</a><a href="/conta">Minha conta</a></div></footer>
 </main>}
