import LaunchCountdown from "./LaunchCountdown";
import {serverRates,serverSystems,siteConfig} from "./config/site";
import {getServerStatus} from "./lib/game-account";
import HeaderAuth from "./HeaderAuth";
const topics=[["OFICIAL","Informações gerais do servidor","Equipe Echelon · Atualizado hoje","cyan"],["GUIA","Como instalar e começar a jogar","12 respostas · 328 visualizações","violet"],["COMUNIDADE","Recrutamento de guildas","38 respostas · há 18 min","amber"]];
const Brand=()=> <span className="brand"><span className="brand-mark">RF</span><span className="brand-copy"><strong>ECHELON</strong><small>PRIVATE SERVER</small></span></span>;
const navLinks:[string,string,string][]=[["#inicio","Início","M3 11l9-8 9 8M5 10v10h5v-6h4v6h5V10"],["/informacoes","Informações","M12 16v-4M12 8h.01M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z"],["#download","Download","M12 3v12M7 10l5 5 5-5M4 20h16"],["/forum","Fórum","M21 12a8 8 0 0 1-11.6 7.1L4 20l1-4.6A8 8 0 1 1 21 12z"],["/gamecp","Game CP","M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM19 12l2-1-2-4-2 .6a7 7 0 0 0-1.6-1L15 4h-4l-.4 2.6a7 7 0 0 0-1.6 1L7 7 5 11l2 1a7 7 0 0 0 0 2l-2 1 2 4 2-.6a7 7 0 0 0 1.6 1L11 21h4l.4-2.6a7 7 0 0 0 1.6-1l2 .6 2-4-2-1a7 7 0 0 0 0-2z"]];
const rateOf=(l:string)=>serverRates.find(r=>r.label.startsWith(l))?.value??"—";
const heroRates:[string,string][]=[["XP",rateOf("Experiência")],["DROP",rateOf("Drop")],["PT / SKILL",rateOf("PT")]];
export default async function Home(){
 const live=await getServerStatus();
 return <main className="home-page" id="conteudo">
 <section className="hero2" id="inicio">
  <div className="hero2-top">
   <div className="hero2-status"><span className={`pulse${live.online?"":" off"}`}/> SERVIDOR <b className={live.online?"on":"off"}>{live.online===null?"INDISPONÍVEL":live.online?"ONLINE":"OFFLINE"}</b><span className="hero2-abertura"><i/>ABERTURA OFICIAL <b className="gold">{siteConfig.launchLabel}</b></span></div>
   <div className="hero2-tools"><span className="lang-switch"><b>PT</b><a href="/en">EN</a></span><HeaderAuth /></div>
  </div>
  <div className="hero2-logo"><span className="brand-mark">RF</span><div><strong>ECHELON</strong><small>PRIVATE SERVER</small></div></div>
  <p className="hero2-side hero2-side-l">MAIS QUE<br/>UM JOGO.<br/>UMA NOVA ERA.</p>
  <p className="hero2-side hero2-side-r">RAÇAS<br/>CONFLITOS<br/>PODER<br/>SEM LIMITES</p>
  <div className="hero2-launch"><span className="hero2-launch-label">ABERTURA OFICIAL</span><LaunchCountdown/><p><i/>UMA NOVA ERA COMEÇA EM <b>02/10</b><i/></p></div>
  <nav className="hero2-nav" aria-label="Navegação principal">{navLinks.map(([href,label,icon])=><a key={href} href={href} className={href==="#inicio"?"active":undefined}><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={icon}/></svg>{label}</a>)}<a className="hero2-cta" href="/gamecp"><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M15 19v-1a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v1M9 10a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM19 8v6M22 11h-6"/></svg>CRIAR CONTA <b>›</b></a></nav>
  <div className="hero2-cards">
   <div className="hero2-card"><h3>STATUS DO SERVIDOR</h3><strong className={`hero2-big ${live.online?"on":"off"}`}><span className="hero2-dot"/>{live.online===null?"INDISPONÍVEL":live.online?"ONLINE":"OFFLINE"}</strong>{live.online?<p className="hero2-note">JOGADORES ONLINE <b>{live.playersOnline}</b></p>:<p className="hero2-note">ABERTURA OFICIAL<b className="gold">{siteConfig.launchLabel}</b></p>}<small className="hero2-foot">Prepare-se. Uma nova era está chegando.</small></div>
   <div className="hero2-card"><h3>TAXAS</h3><div className="hero2-rates">{heroRates.map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</div><small className="hero2-foot">Evolução equilibrada para todos.</small></div>
   <div className="hero2-card hero2-banner"><span className="hero2-banner-kicker">CONHEÇA O</span><h2>RF ECHELON</h2><p>Um mundo em conflito.<br/>Grandes batalhas.<br/>Novas histórias.</p><a className="hero2-more" href="/forum">SAIBA MAIS <b>→</b></a></div>
  </div>
  <div className="hero2-bottom"><span>RF ECHELON <i/> PRIVATE SERVER</span><div/><span>JUNTOS POR UM NOVO AMANHÃ</span></div>
 </section>
 <section className="section rates" id="taxas"><div className="section-intro"><span className="kicker">CONFIGURAÇÃO DO SERVIDOR</span><h2>Taxas pensadas pro <em>late game.</em></h2><p>Evolução rápida sem perder o desafio — confira as taxas e sistemas ativos no RF Echelon.</p></div><div className="rate-grid">{serverRates.map(r=><div className="rate-card" key={r.label}><span className="rate-value">{r.value}</span><span className="rate-label">{r.label}</span></div>)}</div><div className="system-list"><span className="mini-label">SISTEMAS</span><div className="system-grid">{serverSystems.map(s=><div className="system-card" key={s.name}><span className="system-icon">{s.icon}</span><strong>[{s.name}]</strong><div className="system-card-row"><span>Status</span><b className={`system-status ${s.active?"on":"off"}`}>{s.active?"Ativo":"Desativado"}</b></div>{"detail" in s&&<p>{s.detail}</p>}{"guidePath" in s&&<a className="system-card-link" href={s.guidePath}>Ver detalhes <span>→</span></a>}</div>)}</div></div><p className="rates-note">E muitos outros recursos — com mais chegando.</p></section>
 <section className="section download" id="download"><div className="section-intro"><span className="kicker">COMECE SUA JORNADA</span><h2>Pronto para a <em>batalha?</em></h2><p>Baixe o cliente completo e crie sua conta pra entrar em Novus.</p></div><div className="download-panel"><div className="file-icon">⬇</div><div><span className="mini-label">CLIENTE COMPLETO</span><h3>RF Echelon Client</h3><p>Extraia o .rar e rode o client — sem instalador.</p></div><a className="btn btn-primary" href="https://www.mediafire.com/file/s7x4acfu0nms7ej/RFEchelonfull.rar/file" target="_blank" rel="noopener noreferrer">Baixar cliente <span>↓</span></a></div><div className="download-panel" style={{marginTop:14}}><div className="file-icon">⬇</div><div><span className="mini-label">LAUNCHER</span><h3>RF Echelon Launcher</h3><p>Extraia o .rar e use pra entrar no jogo.</p></div><a className="btn btn-primary" href="https://www.mediafire.com/file/h2kqqd627npfcn3/rfechelon.rar/file" target="_blank" rel="noopener noreferrer">Baixar launcher <span>↓</span></a></div><div className="requirements"><span><b>01</b> Crie sua conta em /conta</span><span><b>02</b> Baixe cliente e launcher</span><span><b>03</b> Entre e escolha sua raça</span></div></section>
 <section className="section donate" id="doacao"><div className="donate-copy"><span className="kicker">APOIE O ECHELON</span><h2>Sua força mantém<br/>este universo <em>vivo.</em></h2><p>As doações ajudam a manter a infraestrutura, segurança e novos eventos. As recompensas não substituem sua evolução dentro do jogo.</p><ul><li>Pagamento seguro</li><li>Crédito automático</li><li>Histórico disponível</li></ul></div><div className="donate-card"><span className="mini-label">PACOTES</span><div className="coins"><span>◈</span><div><strong>Em breve</strong><small>Cash Points + 30 dias Premium</small></div></div><div className="price" style={{fontSize:20}}>Em breve</div><a className="btn btn-gold" href="/gamecp">Saber mais <span>↗</span></a><small className="safe">Abertura em 02/10/2026 às 18:00</small></div></section>
 <section className="section forum" id="forum"><div className="forum-head"><div><span className="kicker">CENTRAL DA COMUNIDADE</span><h2>Últimas do <em>fórum.</em></h2></div><a className="text-link" href="/forum">Ver todos os tópicos ↗</a></div><div className="forum-layout"><div className="topic-list">{topics.map((t,i)=><a className="topic" href={`/forum#topico-${i+1}`} key={t[1]}><span className={`topic-icon ${t[3]}`}>#</span><div><span className="topic-tag">{t[0]}</span><h3>{t[1]}</h3><p>{t[2]}</p></div><b>→</b></a>)}</div><aside className="forum-info"><span className="mini-label">INFORMAÇÕES RÁPIDAS</span><h3>Servidor PvP<br/>com progressão justa.</h3><dl><div><dt>Experiência</dt><dd>10x</dd></div><div><dt>Drop</dt><dd>5x</dd></div><div><dt>Max level</dt><dd>55</dd></div><div><dt>Chip War</dt><dd>3× ao dia</dd></div></dl><a href="/forum#informacoes">Ver informações completas →</a></aside></div></section>
 <footer><a href="#inicio"><Brand/></a><p>© 2026 CCR — Todos os direitos reservados.<br/>RF Online pertence aos seus respectivos proprietários. RF Echelon é um servidor independente criado por fãs.</p><div><a href="#download">Download</a><a href="/forum">Fórum</a><a href="/gamecp">Game CP</a></div></footer>
 </main>}
