const packs=[
 ["INICIANTE","49.900","R$ 49,90","SEM BÔNUS","49.900",[["◈","Anel do Novato"],["✦","Capa Ascension"],["◆","Poção Premium x20"]]],
 ["ASCENDENTE","109.900","R$ 109,90","+10% CASH","120.890",[["⚔","Arma Visual Éter"],["⬡","Relíquia de Novus"],["✦","Poção Premium x50"]]],
 ["DOMINADOR","179.900","R$ 179,90","+15% CASH","206.885",[["♜","Armadura Cerimonial"],["◉","Drone de Combate"],["◆","Caixa Rara x3"]]],
 ["IMPERADOR","300.000","R$ 300,00","+30% CASH","390.000",[["♛","Coroa de Novus"],["◇","Asas do Eclipse"],["⬢","Montaria Mecânica"]]]
];
const Brand=()=> <span className="brand"><span className="brand-mark">RF</span><span className="brand-copy"><strong>ASCENSION</strong><small>PRIVATE SERVER</small></span></span>;
export default function Donation(){return <main className="premium-donation">
 <header className="site-header"><a href="/"><Brand/></a><nav><a href="/">Início</a><a href="/#download">Download</a><a className="active" href="/doacao">Doação</a><a href="/forum">Fórum</a><a href="/conta">Minha conta</a></nav><div className="header-tools"><span className="lang-switch"><b>PT</b><a href="/en/donate">EN</a></span><a className="header-cta" href="/conta">Minha conta <span>↗</span></a></div></header>
 <section className="donation-hero"><div className="donation-orbit"/><div className="donation-copy"><span className="kicker">CENTRAL DE CONTRIBUIÇÕES · ACESSO PREMIUM</span><h1>Fortaleça o<br/><em>RF Ascension.</em></h1><p>Sua contribuição mantém Novus online, protegido e em constante evolução. Escolha seu pacote e receba seus Cash Points automaticamente.</p><div className="trust-line"><span>◆ PAGAMENTO SEGURO</span><span>◆ ENTREGA AUTOMÁTICA</span><span>◆ SUPORTE DA EQUIPE</span></div></div><aside className="donation-balance"><div className="vip-sigil">◈<span>ASCENSION<br/>VAULT</span></div><span>SALDO DA CONTA</span><strong>0 <small>CP</small></strong><p>Entre na sua conta para consultar seu saldo e histórico.</p><div className="balance-meta"><span>STATUS <b>SEGURO</b></span><span>ENTREGA <b>IMEDIATA</b></span></div><a href="/conta" className="corner-button">ACESSAR MINHA CONTA <b>↗</b></a></aside><div className="premium-stats"><span><b>01</b> Selecione o pacote</span><span><b>02</b> Confirme o pagamento</span><span><b>03</b> Receba seus Cash Points</span></div></section>
 <section className="donation-store"><header><div><span className="kicker">COLEÇÃO ASCENSION</span><h2>Escolha seu poder.</h2></div><p>Cash avulso: R$ 1 por 1.000 Cash. Os pacotes incluem itens exclusivos que não aparecem na loja comum.</p></header><div className="cash-rate"><span>COTAÇÃO FIXA</span><strong>R$ 1,00</strong><i>=</i><b>1.000 CASH</b><small>Todos os pacotes respeitam a mesma cotação e adicionam recompensas exclusivas.</small></div><div className="pack-grid">{packs.map((p,i)=><article className={`cash-pack tier-${i+1} ${i===3?"featured":""}`} key={p[0]}>{i===3&&<span className="popular">TOP TIER</span>}<div className="pack-top"><span>{p[0]}</span><i>RF // 0{i+1}</i></div><div className="pack-emblem"><span>{["◈","⚔","♜","♛"][i]}</span></div><div className="cash-value"><b>◈</b><strong>{p[4]}</strong><small>CASH TOTAL RECEBIDO</small></div><div className="cash-breakdown"><span>BASE <b>{p[1]}</b></span><span>{p[3]}</span></div><div className="pack-price">{p[2]} <small>pagamento único</small></div><div className="premium-included"><i>♛</i><span><strong>30 DIAS PREMIUM</strong><small>INCLUÍDO EM TODOS OS PACOTES</small></span></div><div className="exclusive-label"><span>CONTEÚDO EXCLUSIVO</span><small>FORA DA CASH SHOP</small></div><ul className="exclusive-items">{p[5].map((item)=><li key={item[1]}><i>{item[0]}</i><span>{item[1]}<small>ITEM EXCLUSIVO</small></span></li>)}</ul><button className="corner-button">SELECIONAR PACOTE <b>→</b></button></article>)}</div>
 <div className="payment-bar"><span>FORMAS DE PAGAMENTO</span><b>PIX</b><b>Cartão</b><b>Mercado Pago</b><small>Ambiente protegido e confirmação automática</small></div></section>
 <section className="donation-values"><div><span className="kicker">CONTRIBUIÇÃO TRANSPARENTE</span><h2>O servidor cresce<br/>com a comunidade.</h2></div><div className="value-list"><article><b>01</b><h3>Infraestrutura</h3><p>Servidores estáveis, baixa latência e proteção contra ataques.</p></article><article><b>02</b><h3>Conteúdo</h3><p>Novos eventos, melhorias e atualizações frequentes.</p></article><article><b>03</b><h3>Jogo justo</h3><p>As recompensas apoiam sua jornada sem substituir a evolução.</p></article></div></section>
 </main>}
