const Brand=()=> <span className="brand"><span className="brand-mark">RF</span><span className="brand-copy"><strong>ASCENSION</strong><small>PRIVATE SERVER</small></span></span>;
const topics=[["OFFICIAL","General server information","Ascension Team · Updated today","cyan"],["GUIDE","How to install and start playing","12 replies · 328 views","violet"],["COMMUNITY","Guild recruitment","38 replies · 18 min ago","amber"]];
const rates=[["10x","Experience (XP)"],["x4","Sell (original value)"],["x3","PT / Skill"],["x5","Drop"],["16","Party members"],["16","Active buffs"],["100","Guild members"],["255","Item stack"]];
const systems=[["Consil Armor",false,""],["CCR Box",false,""],["New Item System",true,"Talic Upgrade (with new talics), Rune System and Rank Up System."],["Extended Special Effects",true,"Up to 10 special effects per item."],["Auto Rollup Special Effects",true,"On drop, box opening and other item sources."],["Guild Passives System",true,""],["Guild Research System",true,""],["Reworked Quests",true,"Every quest on the server was reviewed and redone."],["Daily Quest System",true,""],["Global Boss Announcement",true,"Server-wide alert when a boss spawns and when it dies."],["XP on Maul",true,"You gain experience normally while piloting the Maul."],["Hunter Traps",true,"Can also be used to kill monsters and gain XP."],["Hunter Towers",true,"Can also be used to kill monsters and gain XP."],["Charge Ammo",true,""],["Solo Dungeon",true,""],["PvP Dungeon",true,""],["Module System",true,"RF Ascension's own system, constantly evolving."],["Destroy M.A.U. key on explode",false,""]] as const;
export default function EnglishHome(){return <main className="home-page">
 <header className="site-header"><a href="#home"><Brand/></a><nav><a href="#home">Home</a><a href="#rates">Rates</a><a href="#download">Download</a><a href="/en/donate">Donate</a><a href="/en/forum">Forum</a><a href="/en/account">My account</a></nav><div className="header-tools"><span className="lang-switch"><a href="/">PT</a><b>EN</b></span><a className="header-cta" href="/en/account">Create account <span>↗</span></a></div></header>
 <section className="hero" id="home"><div className="stars"/><div className="hero-content"><div className="eyebrow"><span/> A NEW ERA BEGINS NOW</div><h1>Raise your power.<br/><em>Dominate Novus.</em></h1><p>RF Ascension brings back the classic war between races with balanced progression, a stable economy and epic battles every day.</p><div className="hero-actions"><a className="btn btn-primary" href="#download">Download game <span>↓</span></a><a className="btn btn-ghost" href="/en/forum"><span className="play">▶</span> Discover the server</a></div><div className="season"><span>SEASON 01</span><div/><small>ASCEND. CONQUER. DOMINATE.</small></div></div></section>
 <section className="section rates" id="rates"><div className="section-intro"><span className="kicker">SERVER CONFIGURATION</span><h2>Rates built for the <em>long run.</em></h2><p>Fast progression without losing the challenge — check the rates and active systems on RF Ascension.</p></div><div className="rate-grid">{rates.map(([value,label])=><div className="rate-card" key={label}><span className="rate-value">{value}</span><span className="rate-label">{label}</span></div>)}</div><div className="system-list"><span className="mini-label">SYSTEMS</span>{systems.map(([name,active,detail])=><div className="system-row" key={name}><b className={`system-status ${active?"on":"off"}`}>{active?"ACTIVE":"DISABLED"}</b><span><strong>{name}</strong>{detail&&<p>{detail}</p>}</span></div>)}</div><p className="rates-note">And many other features — with more on the way.</p></section>
 <section className="section download" id="download"><div className="section-intro"><span className="kicker">START YOUR JOURNEY</span><h2>Ready for <em>battle?</em></h2><p>Download the full client, install it and enter the server in just a few minutes.</p></div><div className="download-panel"><div className="file-icon">↓</div><div><span className="mini-label">FULL CLIENT</span><h3>RF Ascension Launcher</h3><p>Windows 10/11 · Automatic updates · 4.8 GB</p></div><a className="btn btn-primary" href="#download">Direct download <span>↓</span></a></div></section>
 <section className="section donate" id="donate"><div className="donate-copy"><span className="kicker">SUPPORT ASCENSION</span><h2>Your strength keeps<br/>this universe <em>alive.</em></h2><p>Donations help maintain infrastructure, security and new events. Rewards do not replace your in-game progression.</p><ul><li>Secure payment</li><li>Automatic credit</li><li>Available history</li></ul></div><div className="donate-card"><span className="mini-label">MOST POPULAR PACKAGE</span><div className="coins"><span>◈</span><div><strong>2,500</strong><small>Cash Points</small></div></div><div className="price"><small>US$</small> 9.90</div><a className="btn btn-gold" href="/en/donate">View packages <span>↗</span></a></div></section>
 <section className="section forum"><div className="forum-head"><div><span className="kicker">COMMUNITY HUB</span><h2>Latest from the <em>forum.</em></h2></div><a className="text-link" href="/en/forum">View all topics ↗</a></div><div className="topic-list">{topics.map((t,i)=><a className="topic" href="/en/forum" key={t[1]}><span className={`topic-icon ${t[3]}`}>#</span><div><span className="topic-tag">{t[0]}</span><h3>{t[1]}</h3><p>{t[2]}</p></div><b>→</b></a>)}</div></section>
 </main>}
